name: Deploy and Test

on:
  push:
    paths:
    - helm-chart/**
    - scripts/**
    - acceptance-tests/**
    - .github/**
    branches: ['000-adapt-cd-workflow']
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: dev
      url: https://dev.renku.ch
    steps:
    - uses: actions/checkout@v2
    - name: deploy renku
      uses: ./actions/deploy-renku
      env:
        KUBECONFIG: "${{ github.workspace }}/renkubot-kube.config"
        RENKU_RELEASE: renku
        RENKU_VALUES_FILE: "${{ github.workspace }}/values.yaml"
        RENKU_VALUES: ${{ secrets.CD_VALUES }}
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        RENKU_BOT_DEV_PASSWORD: ${{ secrets.RENKU_BOT_DEV_PASSWORD }}
        RENKU_ANONYMOUS_SESSIONS: true
        RENKU_TESTS_ENABLED: true
        renku: "@development"
    - name: Notify slack
      if: success()
      env:
        RENKU_SLACK_BOT_TOKEN: ${{ secrets.RENKU_SLACK_BOT_TOKEN }}
      run: |
        curl -X POST https://slack.com/api/chat.postMessage \
             -H "Authorization: Bearer $RENKU_SLACK_BOT_TOKEN" \
             --data "channel=C9U45DL1H" \
             --data "text=https://dev.renku.ch has been updated! :tada:"
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y grep
        pip install yq
    - name: Test
      env:
        RENKU_BOT_DEV_PASSWORD: ${{ secrets.RENKU_BOT_DEV_PASSWORD }}
      run: |
        RENKU_PYTHON_VERSION=v$(cat ./helm-chart/renku/requirements.yaml | yq -r '.dependencies[] | select(.name == "renku-core") | .version')
        RENKU_PYTHON_COMMIT=$(echo $RENKU_PYTHON_VERSION | grep -o -P '(?<=-)[0-9a-fA-F]+') || true
        if [ $RENKU_PYTHON_COMMIT ]; then export RENKU_PYTHON_VERSION=$RENKU_PYTHON_COMMIT; fi
        echo "Passing renku-python version $RENKU_PYTHON_VERSION"

        cd acceptance-tests
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build --build-arg renku_python_ref=${RENKU_PYTHON_VERSION} sbt
        docker-compose run -e RENKU_TEST_URL=https://dev.renku.ch \
                           -e RENKU_TEST_FULL_NAME="Renku Bot" \
                           -e RENKU_TEST_EMAIL="renku@datascience.ch" \
                           -e RENKU_TEST_USERNAME="renku-test" \
                           -e RENKU_TEST_PASSWORD="$RENKU_BOT_DEV_PASSWORD" sbt
    - name: Notify slack
      if: failure()
      env:
        RENKU_SLACK_BOT_TOKEN: ${{ secrets.RENKU_SLACK_BOT_TOKEN }}
      run: |
        curl -X POST https://slack.com/api/chat.postMessage \
             -H "Authorization: Bearer $RENKU_SLACK_BOT_TOKEN" \
             --data "channel=C9U45DL1H" \
             --data "text=Acceptance tests on https://dev.renku.ch failed! :scream_cat:"
    - name: Prepare artifact for packaging on failure
      if: failure()
      run: |
        mkdir acceptance-tests/test-artifacts
        cp acceptance-tests/target/*.png acceptance-tests/test-artifacts 2>/dev/null || :
        cp acceptance-tests/target/*.log acceptance-tests/test-artifacts 2>/dev/null || :
        sudo rm -rf acceptance-tests/target/20*/.renku/cache 2>/dev/null || :
        cp -r acceptance-tests/target/20* acceptance-tests/test-artifacts 2>/dev/null || :
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: test-artifacts
        path: acceptance-tests/test-artifacts
  chart:
    needs: test
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/development'"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Configure build
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --deploy --system --dev
          git config --global user.name renku-bot
          git config --global user.email renku@datascience.ch
      - name: update and test chart
        env:
          HELM_URL: https://charts.helm.sh/stable
          HELM_TGZ: helm-v2.16.1-linux-amd64.tar.gz
          TEMP_DIR: ${{ runner.temp }}
        run: |
          PATH=${{ runner.temp }}/linux-amd64/:$PATH
          scripts/install-helm.sh
          helm dep update helm-chart/renku
          helm dep update helm-chart/gitlab
      - name: Push helm chart and images
        if: github.ref == 'refs/heads/development' && !startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.RENKU_CI_TOKEN }}
          DOCKER_BUILDKIT: "1"
        run: |
          cd charts
          chartpress --push --publish-chart
          chartpress --push --tag latest
      - name: Push tagged helm chart and images
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.RENKU_CI_TOKEN }}
        run: |
          cd charts
          chartpress --push --publish-chart --tag $(echo ${GITHUB_REF} | cut -d'/' -f 3)
